In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.multioutput import MultiOutputClassifier



In [2]:


with open("jimin1.csv", 'r', encoding="utf-8") as read_: #read다음에_는 의미가 없다. read랑 헷갈리지말라고 쓴 것. a 라고 해도 무방.
    text=read_.readlines()

rows=[]
for i in text[1:]:
    rows.append(list(map(int,i.split(",")))) # 이름으로 끝나기 때문에 , 가 없다 그래서 -1로 슬라이싱 해준다.
print(i)

df=pd.DataFrame(rows)
df.columns=["sensor%d"%i for i in range(1,18)]

with open("seong2.csv", 'r', encoding="utf-8") as read_:
    text2=read_.readlines()
    

rows2=[]
for i in text2[1:]:
    rows2.append(list(map(int,i.split(","))))
print(i)

with open("yeon2.csv", 'r', encoding="utf-8") as read_:
    text3=read_.readlines()
    
rows9=[]
for i in text3[1:]:
    rows9.append(list(map(int,i.split(","))))
print(i)

df2=pd.DataFrame(rows2)
df2.columns=["sensor%d"%i for i in range(1,18)]


df3=pd.DataFrame(rows9)
df3.columns=["sensor%d"%i for i in range(1,18)]



 16, 19, 23, 27, 34, 36, 40, 44, 41, 46, 48, 51, 56, 58, 58, 62,2
 79, 80, 80, 80, 82, 81, 81, 81, 78, 80, 79, 79, 80, 83, 82, 82,0

 0, 0, 6, 11, 20, 24, 30, 33, 34, 40, 42, 45, 49, 53, 56, 59,1



In [ ]:
df

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
0        196      189      182      177      171      165      161      156   
1         98      100       99      101      100      101      101      100   
2         59       64       65       66       69       75       71       74   
3          0        6       12       16       24       28       31       37   
4        213      203      196      188      183      177      169      164   
..       ...      ...      ...      ...      ...      ...      ...      ...   
261       81       83       81       83       84       87       84       83   
262       74       77       78       79       80       82       84       84   
263       31       36       39       44       49       54       57       58   
264       13       19       27       24       34       39       43       48   
265       16       19       23       27       34       36       40       44   

     sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
0        149       144       140       135       135       132       128   
1         97        97        98        98       101       101       102   
2         71        74        75        77        79        79        80   
3         36        41        43        48        49        54        56   
4        157       151       146       143       141       137       133   
..       ...       ...       ...       ...       ...       ...       ...   
261       83        83        85        82        88        86        87   
262       82        87        84        86        85        88        88   
263       59        61        64        68        72        71        73   
264       48        51        53        56        61        64        65   
265       41        46        48        51        56        58        58   

     sensor16  sensor17  
0         126         2  
1         102         2  
2          80         2  
3          58         2  
4         130         2  
..        ...       ...  
261        85         2  
262        86         2  
263        76         2  
264        67         2  
265        62         2  

[266 rows x 17 columns]

In [3]:
df = df.iloc[:255,]

In [ ]:
# 20 행마다 잘라서 여러개의 데이터 셋 으로 만들기

In [4]:
df2 = df2.iloc[:255,]
df2

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
0          0        5       12       17       24       32       33       41   
1         75       76       77       78       83       83       82       84   
2         80       84       82       83       85       85       84       85   
3        747      699      657      617      583      550      517      491   
4        450      423      398      377      358      340      322      305   
..       ...      ...      ...      ...      ...      ...      ...      ...   
250       69       72       74       79       77       82       81       81   
251       49       50       53       55       59       62       66       67   
252      151      143      142      138      136      131      128      125   
253      176      170      165      161      154      151      146      142   
254       99       97       96       96       98       97       96       96   

     sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
0         35        43        46        49        52        55        56   
1         82        81        82        82        83        84        84   
2         81        83        84        83        87        87        87   
3        460       438       410       390       371       353       338   
4        287       275       262       250       241       232       221   
..       ...       ...       ...       ...       ...       ...       ...   
250       78        79        82        81        85        90        86   
251       66        66        69        71        74        74        76   
252      117       116       112       112       111       109       107   
253      134       133       127       126       124       121       116   
254       92        91        91        90        93        92        92   

     sensor16  sensor17  
0          57         0  
1          85         0  
2          87         0  
3         322         0  
4         214         0  
..        ...       ...  
250        89         0  
251        77         0  
252       107         0  
253       113         0  
254        90         0  

[255 rows x 17 columns]

In [5]:
df3 = df3.iloc[:255,]
df3

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
0         58       60       62       64       66       68       71       71   
1        100       99       97       99      100       99       98      103   
2         62       63       67       67       71       72       73       74   
3         76       76       78       78       82       82       76       83   
4         55       59       61       67       66       68       70       72   
..       ...      ...      ...      ...      ...      ...      ...      ...   
250      102      102      103      100      103      100       97       98   
251      104      105      103      103      104      103      101      103   
252      117      115      111      111      111      110      107      105   
253      122      120      118      116      117      114      112      111   
254       43       46       50       53       56       56       58       61   

     sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
0         68        70        72        72        76        76        77   
1         93        94        92        91        92        92        92   
2         73        75        76        77        80        80        79   
3         75        81        82        82        84        84        84   
4         70        72        73        74        76        78        79   
..       ...       ...       ...       ...       ...       ...       ...   
250       94        93        93        92        94        96        92   
251       99        97        97        97        97        97        97   
252      102       102       101       100        99        98       101   
253      106       106       103       103       103       102       101   
254       62        60        63        61        71        67        70   

     sensor16  sensor17  
0          78         1  
1          92         1  
2          81         1  
3          85         1  
4          78         1  
..        ...       ...  
250        96         1  
251        96         1  
252        98         1  
253       102         1  
254        71         1  

[255 rows x 17 columns]

# It is quite useful to add a hierarchical index (Also known as multi-level index) for more sophisticated data analysis. In this case, let’s add index Year 1 and Year 2 for df1 and df2 respectively. To do that, we can simply specify the keys argument.

In [ ]:
# frames = [df,df2,df3]
# df_keys = pd.concat(frames, keys = ['1','2','3'])
# df_keys

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
1 0       91.0     93.0     85.0     90.0     95.0     93.0     86.0     91.0   
  1       70.0     73.0     69.0     71.0     76.0     76.0     77.0     78.0   
  2       65.0     64.0     68.0     67.0     72.0     71.0     74.0     73.0   
  3       13.0     19.0     24.0     29.0     35.0     37.0     41.0     47.0   
  4      102.0    100.0    102.0     97.0     99.0     99.0     97.0     96.0   
...        ...      ...      ...      ...      ...      ...      ...      ...   
3 115     59.0     61.0     64.0     67.0     70.0     71.0     72.0     76.0   
  116     63.0     62.0     64.0     64.0     69.0     70.0     73.0     73.0   
  117     75.0     77.0     77.0     80.0     81.0     82.0     82.0     83.0   
  118     18.0     23.0     29.0     34.0     42.0     43.0     45.0     50.0   
  119      5.0     12.0     17.0     22.0     31.0     36.0     40.0     43.0   

       sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
1 0       87.0      87.0      87.0      86.0      88.0      87.0      90.0   
  1       74.0      75.0      76.0      78.0      79.0      80.0      78.0   
  2       73.0      70.0      72.0      74.0      77.0      77.0      78.0   
  3       44.0      48.0      51.0      55.0      58.0      59.0      59.0   
  4       92.0      91.0      89.0      89.0      91.0      91.0      90.0   
...        ...       ...       ...       ...       ...       ...       ...   
3 115     71.0      73.0      73.0      76.0      78.0      78.0      79.0   
  116     73.0      72.0      75.0      76.0      77.0      80.0      79.0   
  117     80.0      80.0      80.0      80.0      83.0      86.0      85.0   
  118     50.0      53.0      59.0      58.0      59.0      65.0      66.0   
  119     44.0      46.0      50.0      54.0      58.0      60.0      62.0   

       sensor16  
1 0        87.0  
  1        81.0  
  2        78.0  
  3        62.0  
  4        88.0  
...         ...  
3 115      78.0  
  116      80.0  
  117      85.0  
  118      69.0  
  119      66.0  

[360 rows x 16 columns]

In [6]:
frames = [df,df2,df3]
df_keys = pd.concat(frames, axis=0) 


In [7]:
df_keys

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
0        196      189      182      177      171      165      161      156   
1         98      100       99      101      100      101      101      100   
2         59       64       65       66       69       75       71       74   
3          0        6       12       16       24       28       31       37   
4        213      203      196      188      183      177      169      164   
..       ...      ...      ...      ...      ...      ...      ...      ...   
250      102      102      103      100      103      100       97       98   
251      104      105      103      103      104      103      101      103   
252      117      115      111      111      111      110      107      105   
253      122      120      118      116      117      114      112      111   
254       43       46       50       53       56       56       58       61   

     sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
0        149       144       140       135       135       132       128   
1         97        97        98        98       101       101       102   
2         71        74        75        77        79        79        80   
3         36        41        43        48        49        54        56   
4        157       151       146       143       141       137       133   
..       ...       ...       ...       ...       ...       ...       ...   
250       94        93        93        92        94        96        92   
251       99        97        97        97        97        97        97   
252      102       102       101       100        99        98       101   
253      106       106       103       103       103       102       101   
254       62        60        63        61        71        67        70   

     sensor16  sensor17  
0         126         2  
1         102         2  
2          80         2  
3          58         2  
4         130         2  
..        ...       ...  
250        96         1  
251        96         1  
252        98         1  
253       102         1  
254        71         1  

[765 rows x 17 columns]

In [ ]:
df_keys

array([[196, 189, 182, ..., 128, 126,   2],
       [ 98, 100,  99, ..., 102, 102,   2],
       [ 59,  64,  65, ...,  80,  80,   2],
       ...,
       [117, 115, 111, ..., 101,  98,   1],
       [122, 120, 118, ..., 101, 102,   1],
       [ 43,  46,  50, ...,  70,  71,   1]])

In [8]:
df_keys = df_keys.to_numpy()

In [9]:
df_keys.shape

(765, 17)

In [48]:
xtrain1 = df_keys.reshape(51,5,3,17)

In [12]:
y_train1 = df_keys[:,16]

In [42]:
y_train1.shape

(765,)

In [ ]:
import missingno as msno

msno.matrix(df)

AttributeError: 'numpy.ndarray' object has no attribute 'notnull'

# msno.matrix(df) 을 통해 결측치가 없음을 확인하였다.



# 해야 할 일


- csv 파일 만들기
- --> 자동으로 data 에 concat 하기
- 그것을 train, test split(주로 train 에 배치)
- test 는 새로 들어온 데이터를 기준으로 함(신원인증 버튼 누르면 1분동안의 새 데이터)
- 레이블링(y_train 의 차원을 x_train 과 맞춰주기 위해서 코딩 필요)
- 자동 레이블링 과정 필요(string(id)-->int)


                            

# 행렬의 20 행 마다 짤라서 사진 만들기(레이블링 추가는 기억 후 나중에 추가 하기 y_train 으로 만들기)







# 나머지 4*16은 x_test

# 라벨은 마지막 열 이용!


In [49]:
xtrain1 = xtrain1.flatten()

In [50]:
xtrain1.shape

(13005,)

In [40]:
y_train1.shape

(765,)

In [47]:
ylabel = y_train1[0:765:15]

In [51]:
xtest = xtrain1

In [52]:
xtest1 = xtest[10200:]

In [36]:
xtrain1 = xtrain1[:10200]

In [53]:
xtest2 = xtest1.reshape(11,5,3,17)

In [38]:
xtrain2 = xtrain1.reshape(40,5,3,17)

In [55]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

#예제

#
#(raw_train, raw_validation, raw_test), metadata = tfds.load(
 #   'cats_vs_dogs',
 #   split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
 #   with_info=True,
 #   as_supervised=True,
# #)
# x_train, x_test, y_train, y_test = train_test_split(df2, y, test_size = 0.4,random_state=42) 
#1). X_train - 여기에는 모든 독립 변수가 포함되며 우리가 지정한 대로 모델을 훈련하는 데 사용되며, 완전한 데이터의 이 관찰 test_size = 0.4수단 60%은 모델을 훈련/적합하는 40%데 사용되고 나머지는 테스트에 사용됩니다. 모델.
#2). X_test40% - 학습 단계에서 사용되지 않고 모델의 정확도를 테스트하기 위한 예측을 수행하는 데 사용되는 데이터의 독립 변수의 나머지 부분입니다.
#3). y_train - 이것은 이 모델에 의해 예측되어야 하는 종속 변수입니다. 여기에는 독립 변수에 대한 범주 레이블이 포함됩니다. 모델을 훈련/피팅하는 동안 종속 변수를 지정해야 합니다.
#4). y_test - 이 데이터에는 테스트 데이터에 대한 범주 레이블이 있으며, 이 레이블은 실제 범주와 예측 범주 간의 정확도를 테스트하는 데 사용됩니다.



(x_train, y_train), (x_test, y_test) = (xtrain2 , ylabel[:13]),(xtest2,ylabel[13:])
# x_train, x_test, y_train, y_test = train_test_split(data, y_train, random_state=random_state, test_size=0.2)
x_train, x_test = x_train / 255.0, x_test / 255.0

print("x_train:", len(x_train), "x_test:", len(x_test))

x_train: 40 x_test: 11


# 여기서 부터 잘생각하자....
# 모든 행의 레이블링을 할 것이냐
# 아니면 차원을 늘려서 할 것이냐


In [ ]:
# df_keys[:, df_keys.columns != 'level_0']
unidata = df_keys.drop('level_0', axis=1)

In [ ]:
label = df_keys.loc[:,'level_0']

# 밑 코드 중요
# x_train, y_train 준비 

In [ ]:
y_train

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
0      91.0     93.0     85.0     90.0     95.0     93.0     86.0     91.0   
1      70.0     73.0     69.0     71.0     76.0     76.0     77.0     78.0   
2      65.0     64.0     68.0     67.0     72.0     71.0     74.0     73.0   
3      13.0     19.0     24.0     29.0     35.0     37.0     41.0     47.0   
4     102.0    100.0    102.0     97.0     99.0     99.0     97.0     96.0   
..      ...      ...      ...      ...      ...      ...      ...      ...   
35     64.0     67.0     68.0     70.0     73.0     73.0     75.0     76.0   
36     65.0     66.0     67.0     69.0     73.0     74.0     74.0     75.0   
37     63.0     65.0     67.0     69.0     72.0     73.0     75.0     75.0   
38     63.0     65.0     68.0     69.0     73.0     74.0     74.0     75.0   
39     65.0     65.0     68.0     70.0     73.0     74.0     75.0     72.0   

    sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
0      87.0      87.0      87.0      86.0      88.0      87.0      90.0   
1      74.0      75.0      76.0      78.0      79.0      80.0      78.0   
2      73.0      70.0      72.0      74.0      77.0      77.0      78.0   
3      44.0      48.0      51.0      55.0      58.0      59.0      59.0   
4      92.0      91.0      89.0      89.0      91.0      91.0      90.0   
..      ...       ...       ...       ...       ...       ...       ...   
35     74.0      74.0      75.0      76.0      80.0      80.0      80.0   
36     74.0      75.0      76.0      78.0      79.0      80.0      81.0   
37     74.0      75.0      74.0      77.0      77.0      79.0      79.0   
38     73.0      74.0      76.0      76.0      79.0      80.0      81.0   
39     74.0      76.0      76.0      78.0      79.0      80.0      81.0   

    sensor16  
0       87.0  
1       81.0  
2       78.0  
3       62.0  
4       88.0  
..       ...  
35      81.0  
36      82.0  
37      82.0  
38      81.0  
39      81.0  

[280 rows x 16 columns]

In [ ]:
label = label[:285]

In [ ]:
label 

0     1
1     1
2     1
3     1
4     1
     ..
40    3
41    3
42    3
43    3
44    3
Name: level_0, Length: 285, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split


(x_train, x_test), (y_train, y_test) = (df_keys[0:285], df_keys[285:]),(label[0:285], label[285:])


In [ ]:
x_train = x_train.drop('level_0', axis = 1)

In [ ]:
x_train

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
0      91.0     93.0     85.0     90.0     95.0     93.0     86.0     91.0   
1      70.0     73.0     69.0     71.0     76.0     76.0     77.0     78.0   
2      65.0     64.0     68.0     67.0     72.0     71.0     74.0     73.0   
3      13.0     19.0     24.0     29.0     35.0     37.0     41.0     47.0   
4     102.0    100.0    102.0     97.0     99.0     99.0     97.0     96.0   
..      ...      ...      ...      ...      ...      ...      ...      ...   
40     62.0     64.0     67.0     69.0     72.0     73.0     74.0     76.0   
41     63.0     65.0     68.0     69.0     71.0     74.0     75.0     76.0   
42     63.0     65.0     67.0     68.0     70.0     73.0     76.0     75.0   
43     62.0     65.0     65.0     69.0     72.0     73.0     75.0     76.0   
44     62.0     64.0     67.0     68.0     72.0     72.0     73.0     74.0   

    sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
0      87.0      87.0      87.0      86.0      88.0      87.0      90.0   
1      74.0      75.0      76.0      78.0      79.0      80.0      78.0   
2      73.0      70.0      72.0      74.0      77.0      77.0      78.0   
3      44.0      48.0      51.0      55.0      58.0      59.0      59.0   
4      92.0      91.0      89.0      89.0      91.0      91.0      90.0   
..      ...       ...       ...       ...       ...       ...       ...   
40     75.0      77.0      75.0      79.0      80.0      83.0      79.0   
41     74.0      74.0      76.0      76.0      78.0      81.0      81.0   
42     73.0      75.0      76.0      78.0      77.0      82.0      81.0   
43     73.0      72.0      75.0      76.0      79.0      80.0      80.0   
44     72.0      74.0      73.0      75.0      80.0      80.0      80.0   

    sensor16  
0       87.0  
1       81.0  
2       78.0  
3       62.0  
4       88.0  
..       ...  
40      81.0  
41      81.0  
42      79.0  
43      80.0  
44      81.0  

[285 rows x 16 columns]

In [ ]:
df_keys

level_0  sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  \
0         1     91.0     93.0     85.0     90.0     95.0     93.0     86.0   
1         1     70.0     73.0     69.0     71.0     76.0     76.0     77.0   
2         1     65.0     64.0     68.0     67.0     72.0     71.0     74.0   
3         1     13.0     19.0     24.0     29.0     35.0     37.0     41.0   
4         1    102.0    100.0    102.0     97.0     99.0     99.0     97.0   
..      ...      ...      ...      ...      ...      ...      ...      ...   
115       3     59.0     61.0     64.0     67.0     70.0     71.0     72.0   
116       3     63.0     62.0     64.0     64.0     69.0     70.0     73.0   
117       3     75.0     77.0     77.0     80.0     81.0     82.0     82.0   
118       3     18.0     23.0     29.0     34.0     42.0     43.0     45.0   
119       3      5.0     12.0     17.0     22.0     31.0     36.0     40.0   

     sensor8  sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  \
0       91.0     87.0      87.0      87.0      86.0      88.0      87.0   
1       78.0     74.0      75.0      76.0      78.0      79.0      80.0   
2       73.0     73.0      70.0      72.0      74.0      77.0      77.0   
3       47.0     44.0      48.0      51.0      55.0      58.0      59.0   
4       96.0     92.0      91.0      89.0      89.0      91.0      91.0   
..       ...      ...       ...       ...       ...       ...       ...   
115     76.0     71.0      73.0      73.0      76.0      78.0      78.0   
116     73.0     73.0      72.0      75.0      76.0      77.0      80.0   
117     83.0     80.0      80.0      80.0      80.0      83.0      86.0   
118     50.0     50.0      53.0      59.0      58.0      59.0      65.0   
119     43.0     44.0      46.0      50.0      54.0      58.0      60.0   

     sensor15  sensor16  
0        90.0      87.0  
1        78.0      81.0  
2        78.0      78.0  
3        59.0      62.0  
4        90.0      88.0  
..        ...       ...  
115      79.0      78.0  
116      79.0      80.0  
117      85.0      85.0  
118      66.0      69.0  
119      62.0      66.0  

[360 rows x 17 columns]

In [ ]:
y_train

31     2
34     1
87     1
57     1
101    3
      ..
3      2
80     3
15     1
5      2
25     3
Name: level_0, Length: 288, dtype: object

In [ ]:
xtrain = x_train.copy()
ytrain = y_train.copy()

In [ ]:
y_train.astype('float64')

31     2.0
34     1.0
87     1.0
57     1.0
101    3.0
      ... 
3      2.0
80     3.0
15     1.0
5      2.0
25     3.0
Name: level_0, Length: 288, dtype: float64

In [ ]:
print("x_train:", len(x_train), "x_test:", len(x_test))

x_train: 288 x_test: 72


In [ ]:
ytrain.astype("float64")

31     2.0
34     1.0
87     1.0
57     1.0
101    3.0
      ... 
3      2.0
80     3.0
15     1.0
5      2.0
25     3.0
Name: level_0, Length: 288, dtype: float64

In [ ]:
ytrain.dtype

dtype('O')

In [ ]:
y_train.shape

(288,)

In [ ]:
# y_train = np.ones([19,16])

In [ ]:
x_train


sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
31      71.0     74.0     74.0     76.0     77.0     80.0     79.0     80.0   
34      67.0     70.0     71.0     72.0     76.0     76.0     79.0     78.0   
87      59.0     61.0     65.0     66.0     68.0     70.0     71.0     74.0   
57      44.0     48.0     51.0     54.0     58.0     61.0     64.0     65.0   
101     63.0     65.0     67.0     70.0     71.0     72.0     73.0     75.0   
..       ...      ...      ...      ...      ...      ...      ...      ...   
3       70.0     72.0     72.0     73.0     76.0     78.0     78.0     79.0   
80      62.0     64.0     67.0     67.0     72.0     71.0     76.0     74.0   
15      63.0     63.0     68.0     68.0     70.0     71.0     76.0     75.0   
5       87.0     88.0     86.0     86.0     89.0     89.0     89.0     90.0   
25      62.0     62.0     63.0     66.0     70.0     73.0     73.0     74.0   

     sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  sensor15  \
31      77.0      78.0      79.0      79.0      82.0      82.0      83.0   
34      78.0      76.0      76.0      77.0      81.0      81.0      84.0   
87      70.0      71.0      72.0      74.0      77.0      78.0      77.0   
57      63.0      65.0      67.0      69.0      72.0      73.0      74.0   
101     74.0      75.0      76.0      76.0      80.0      81.0      83.0   
..       ...       ...       ...       ...       ...       ...       ...   
3       77.0      80.0      78.0      81.0      81.0      83.0      82.0   
80      74.0      74.0      75.0      76.0      80.0      81.0      81.0   
15      74.0      74.0      75.0      75.0      78.0      78.0      79.0   
5       87.0      86.0      86.0      84.0      91.0      90.0      89.0   
25      72.0      73.0      75.0      77.0      79.0      81.0      82.0   

     sensor16  
31       83.0  
34       84.0  
87       79.0  
57       75.0  
101      79.0  
..        ...  
3        85.0  
80       82.0  
15       80.0  
5        88.0  
25       82.0  

[288 rows x 16 columns]

In [ ]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
x_train

sensor1   sensor2   sensor3   sensor4   sensor5   sensor6   sensor7  \
31   0.278431  0.290196  0.290196  0.298039  0.301961  0.313725  0.309804   
34   0.262745  0.274510  0.278431  0.282353  0.298039  0.298039  0.309804   
87   0.231373  0.239216  0.254902  0.258824  0.266667  0.274510  0.278431   
57   0.172549  0.188235  0.200000  0.211765  0.227451  0.239216  0.250980   
101  0.247059  0.254902  0.262745  0.274510  0.278431  0.282353  0.286275   
..        ...       ...       ...       ...       ...       ...       ...   
3    0.274510  0.282353  0.282353  0.286275  0.298039  0.305882  0.305882   
80   0.243137  0.250980  0.262745  0.262745  0.282353  0.278431  0.298039   
15   0.247059  0.247059  0.266667  0.266667  0.274510  0.278431  0.298039   
5    0.341176  0.345098  0.337255  0.337255  0.349020  0.349020  0.349020   
25   0.243137  0.243137  0.247059  0.258824  0.274510  0.286275  0.286275   

      sensor8   sensor9  sensor10  sensor11  sensor12  sensor13  sensor14  \
31   0.313725  0.301961  0.305882  0.309804  0.309804  0.321569  0.321569   
34   0.305882  0.305882  0.298039  0.298039  0.301961  0.317647  0.317647   
87   0.290196  0.274510  0.278431  0.282353  0.290196  0.301961  0.305882   
57   0.254902  0.247059  0.254902  0.262745  0.270588  0.282353  0.286275   
101  0.294118  0.290196  0.294118  0.298039  0.298039  0.313725  0.317647   
..        ...       ...       ...       ...       ...       ...       ...   
3    0.309804  0.301961  0.313725  0.305882  0.317647  0.317647  0.325490   
80   0.290196  0.290196  0.290196  0.294118  0.298039  0.313725  0.317647   
15   0.294118  0.290196  0.290196  0.294118  0.294118  0.305882  0.305882   
5    0.352941  0.341176  0.337255  0.337255  0.329412  0.356863  0.352941   
25   0.290196  0.282353  0.286275  0.294118  0.301961  0.309804  0.317647   

     sensor15  sensor16  
31   0.325490  0.325490  
34   0.329412  0.329412  
87   0.301961  0.309804  
57   0.290196  0.294118  
101  0.325490  0.309804  
..        ...       ...  
3    0.321569  0.333333  
80   0.317647  0.321569  
15   0.309804  0.313725  
5    0.349020  0.345098  
25   0.321569  0.321569  

[288 rows x 16 columns]

In [ ]:
x_train.shape



(288, 16)

In [ ]:
#x_train = np.expand_dims(x_train, axis=0)

In [ ]:

print(y_train.shape)


print(x_train.shape)


(280, 16)
(280, 16)


In [ ]:
# y_train 은 (48,) 가 되어야 함!!! 

In [ ]:
y_train = np.array(y_train)
y_train = y_train.reshape(48,)

In [ ]:
y_train

In [ ]:
y_train = pd.DataFrame(y_train)

In [ ]:
y_train 

In [ ]:

y_train = np.expand_dims(y_train, axis=0)

print(y_train.shape)


x_train = np.expand_dims(x_train, axis=0)

print(x_train.shape)


(1, 1, 48, 16)
(1, 1, 48, 16)


In [ ]:

y_train = np.expand_dims(y_train, axis=2)

print(y_train.shape)


x_train = np.expand_dims(x_train, axis=2)

print(x_train.shape)

(48, 16, 1)
(48, 16, 1)


In [ ]:
x_train

array([[[96],
        [94],
        [92],
        [92],
        [93],
        [93],
        [95],
        [92],
        [90],
        [89],
        [89],
        [88],
        [89],
        [92],
        [91],
        [90]],

       [[63],
        [64],
        [66],
        [68],
        [70],
        [73],
        [72],
        [78],
        [71],
        [73],
        [72],
        [72],
        [79],
        [78],
        [78],
        [79]],

       [[167],
        [163],
        [157],
        [151],
        [149],
        [145],
        [139],
        [136],
        [130],
        [127],
        [122],
        [120],
        [120],
        [120],
        [115],
        [117]],

       [[70],
        [71],
        [72],
        [72],
        [76],
        [76],
        [77],
        [77],
        [74],
        [74],
        [71],
        [76],
        [81],
        [79],
        [80],
        [80]],

       [[50],
        [52],
        [55],
        [58],
        [60],
        [6

In [ ]:

print('-'*90)
print('x_train')
print(x_train.shape)

print('-'*90)

print(x_data.shape)

print('-'*90)


print('y_train')
print(y_train.shape)

print('-'*90)


In [ ]:
# x_train 을 float 32 로 바꿔야 함 !!! 

x_train = x_train.astype('float')
y_train = y_train.astype('float')




In [ ]:
x_train

array([[[[0.06933594, 0.07226562, 0.07226562],
         [0.07421875, 0.07519531, 0.078125  ],
         [0.07714844, 0.078125  , 0.07519531],
         ...,
         [0.07226562, 0.06835938, 0.06933594],
         [0.0703125 , 0.07226562, 0.07519531],
         [0.07617188, 0.07519531, 0.07714844]],

        [[0.04296875, 0.046875  , 0.04980469],
         [0.05273438, 0.05664062, 0.05957031],
         [0.0625    , 0.06347656, 0.06152344],
         ...,
         [0.06347656, 0.06542969, 0.06445312],
         [0.0703125 , 0.06738281, 0.07226562],
         [0.07226562, 0.06933594, 0.07421875]],

        [[0.05859375, 0.06054688, 0.0625    ],
         [0.06445312, 0.06738281, 0.06933594],
         [0.06933594, 0.07226562, 0.06835938],
         ...,
         [0.0703125 , 0.06933594, 0.0703125 ],
         [0.07128906, 0.07324219, 0.07714844],
         [0.07617188, 0.07617188, 0.07714844]],

        [[0.06347656, 0.06542969, 0.06542969],
         [0.06835938, 0.07226562, 0.07421875],
         [0.

In [ ]:
print(y_train.shape) # 300개의 행 1개의 열 데이터 
print(x_train.shape) #300개의 행 16개의 열 데이터 

(96, 3, 4)
(96, 1, 16, 3)


In [ ]:

x_train = np.expand_dims(x_train, axis=0)

print(x_train.shape)


(1, 288, 16)


In [ ]:

y_train = np.expand_dims(y_train, axis=0)

print(y_train.shape)


(1, 288)


In [ ]:
type(x_train)

numpy.ndarray

In [ ]:

y_train = np.expand_dims(y_train, axis=0)

print(y_train.shape)

(1, 36, 8)


In [ ]:

y_train = y_train.reshape(96,3)

In [ ]:

x_train = np.expand_dims(x_train, axis=0)

print(x_train.shape)



x_train = x_train.reshape(36,8,16)
print(x_train.shape)

(1, 36, 8, 16)
(36, 8, 16)


In [ ]:
x_train = x_train.reshape(285,2,2,4)
print(x_train.shape)

(285, 2, 2, 4)


In [ ]:

x_train = np.expand_dims(x_train, axis=1)

print(x_train.shape)



(285, 1, 1, 16)


In [ ]:
y_train = y_train.reshape(96,3)
print(y_train.shape)

(96, 3)


In [ ]:
print(x_train.shape)
print(label.shape)

(280, 16)
(280,)


In [ ]:

y_train = np.expand_dims(y_train, axis=0)

print(y_train.shape)


x_train = np.expand_dims(x_train, axis=0)

print(x_train.shape)


(1, 36, 8, 1)
(1, 36, 8, 16)


In [ ]:
## x = keras.layers.Conv1D(64, 1, activation='relu')(img_input)
## 1,3로 하면 정확도 0 이 됨 2 로 할 것 



# 1d CNN(한 행에 대해서 이동)

# 2d CNN(정사각형 필터) 



In [ ]:
print(label.shape)
print(x_train.shape)

(285,)
(285, 16)


# x,y 의 데이터 개수가 같아야 함 지금은 96개
# 마지막의 차원이 같아야 함(3, dense output 클래스 개수)


In [ ]:
y_train = y_train.reshape(96,3)

In [ ]:
print(y_train.shape)
print(x_train.shape)

x_train = x_train.reshape(20,15,16)
y_train = y_train.reshape(20,15,1)

(1, 300, 1)
(1, 300, 16)


In [ ]:
print(y_train.shape)
print(x_train.shape)
prin(ytrain.shape)
display = y_train.sqeeze(new_train_x[0])#.sqeeze 확인
display.shape

(1, 36, 8, 1)
(1, 36, 8, 16)


NameError: name 'prin' is not defined

In [ ]:
x_train.shape

(16, 6, 16, 3)

In [ ]:
label 

0      1
1      1
2      1
3      1
4      1
      ..
115    3
116    3
117    3
118    3
119    3
Name: level_0, Length: 360, dtype: object

In [ ]:
label.shape

(360,)

In [ ]:

x_train = x_train.reshape(16, 6, 16, 3)


In [ ]:
ylabel = [0,0,0,0,0,0,0,0,1,1,1,1,1,1,2,2]
ylabel = np.array(ylabel)
ylabel.shape

(16,)

In [ ]:
y_train = np.argmax(y_train, axis=1)

In [ ]:
y_train

array([[[2.],
        [1.],
        [1.],
        [1.],
        [3.],
        [3.],
        [2.],
        [2.]],

       [[2.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [2.]],

       [[3.],
        [2.],
        [1.],
        [1.],
        [3.],
        [2.],
        [1.],
        [1.]],

       [[2.],
        [1.],
        [2.],
        [3.],
        [2.],
        [3.],
        [3.],
        [2.]],

       [[2.],
        [3.],
        [2.],
        [2.],
        [2.],
        [3.],
        [2.],
        [2.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [3.],
        [3.],
        [3.]],

       [[3.],
        [2.],
        [2.],
        [3.],
        [2.],
        [1.],
        [2.],
        [3.]],

       [[1.],
        [1.],
        [1.],
        [3.],
        [2.],
        [1.],
        [2.],
        [1.]],

       [[1.],
        [3.],
        [1.],
        [2.],
        [1.],
        [2.],
    

In [ ]:
x_train = x_train/1024

x_train

array([[[[0.06933594, 0.07226562, 0.07226562],
         [0.07421875, 0.07519531, 0.078125  ],
         [0.07714844, 0.078125  , 0.07519531],
         ...,
         [0.07226562, 0.06835938, 0.06933594],
         [0.0703125 , 0.07226562, 0.07519531],
         [0.07617188, 0.07519531, 0.07714844]]],


       [[[0.04296875, 0.046875  , 0.04980469],
         [0.05273438, 0.05664062, 0.05957031],
         [0.0625    , 0.06347656, 0.06152344],
         ...,
         [0.06347656, 0.06542969, 0.06445312],
         [0.0703125 , 0.06738281, 0.07226562],
         [0.07226562, 0.06933594, 0.07421875]]],


       [[[0.05859375, 0.06054688, 0.0625    ],
         [0.06445312, 0.06738281, 0.06933594],
         [0.06933594, 0.07226562, 0.06835938],
         ...,
         [0.0703125 , 0.06933594, 0.0703125 ],
         [0.07128906, 0.07324219, 0.07714844],
         [0.07617188, 0.07617188, 0.07714844]]],


       ...,


       [[[0.05664062, 0.05859375, 0.06152344],
         [0.0625    , 0.06640625, 0.066


# 최대한 많은 데이터 확보가 중요함!!!
# 밑의 CNN 모델을 쓸 것입니다 


In [ ]:
img_input = keras.Input(shape=(5,1,3))  # (a,b,c) a는 개수, b는 row ,
# c는 column c는 dense 출력층 개수와 똑같아야한다 


x = keras.layers.Conv2D(128, (2,2),padding="same",activation='relu')(img_input) #256 filters, 5 kernel size, window stride 1 (defalut)
x = keras.layers.MaxPool2D(2, padding= 'same')(x)
x = keras.layers.Conv2D(32, (2,2), padding="same",activation='relu')(x)
x = keras.layers.MaxPool2D(2, padding= 'same')(x)
x = keras.layers.Conv2D(16, (1,1),padding="same", activation='relu')(x)
x = keras.layers.MaxPool2D(2, padding= 'same')(x)

x = keras.layers.Flatten()(x)
x = keras.layers.Dense(48, activation='relu')(x)
x = keras.layers.Flatten()(x)
predictions = keras.layers.Dense(3, activation='softmax')(x) 

model = keras.Model(inputs=img_input, outputs=predictions)

model.summary()

Model: "model_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_23 (InputLayer)        [(None, 5, 1, 3)]         0         
_________________________________________________________________
conv2d_64 (Conv2D)           (None, 5, 1, 128)         1664      
_________________________________________________________________
max_pooling2d_64 (MaxPooling (None, 3, 1, 128)         0         
_________________________________________________________________
conv2d_65 (Conv2D)           (None, 3, 1, 32)          16416     
_________________________________________________________________
max_pooling2d_65 (MaxPooling (None, 2, 1, 32)          0         
_________________________________________________________________
conv2d_66 (Conv2D)           (None, 2, 1, 16)          528       
_________________________________________________________________
max_pooling2d_66 (MaxPooling (None, 1, 1, 16)          0  

In [ ]:
y_train = c1

In [ ]:
img_input = keras.Input(shape=(288,16))  # (a,b,c) a는 개수, b는 row , c는 column


x = keras.layers.Conv1D(32, 5,strides = 2, padding="same",activation='relu')(img_input) #256 filters, 5 kernel size, window stride 1 (defalut)
x = keras.layers.MaxPool1D(2)(x)
x = keras.layers.Conv1D(16, 3, strides = 2, padding="same", activation='relu')(x)
x = keras.layers.MaxPool1D(2)(x)
x = keras.layers.Conv1D(7, 1,strides = 2,padding="same", activation='relu')(x)
x = keras.layers.MaxPool1D(2)(x)

x = keras.layers.Flatten()(x)
x = keras.layers.Dense(64, activation='relu')(x)
x = keras.layers.Flatten()(x)
predictions = keras.layers.Dense(288, activation='softmax')(x)

model = keras.Model(inputs=img_input, outputs=predictions)

model.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 288, 16)]         0         
_________________________________________________________________
conv1d_22 (Conv1D)           (None, 144, 32)           2592      
_________________________________________________________________
max_pooling1d_22 (MaxPooling (None, 72, 32)            0         
_________________________________________________________________
conv1d_23 (Conv1D)           (None, 36, 16)            1552      
_________________________________________________________________
max_pooling1d_23 (MaxPooling (None, 18, 16)            0         
_________________________________________________________________
conv1d_24 (Conv1D)           (None, 9, 7)              119       
_________________________________________________________________
max_pooling1d_24 (MaxPooling (None, 4, 7)              0   

In [ ]:
img_input = keras.Input(shape=(16,1))  # (a,b,c) a는 개수, b는 row , c는 column

# 1d CNN은 한 방향으로 움직이며, time-series 데이터에 사용된다. 인풋/아웃풋 차원은 2차원이다. 
# 그렇다면, 2d CNN 으로 가기위해서는 인풋 데이터가 (라벨 데이터) 다 1,2,3으로 되어야 한다...


x = keras.layers.Conv1D(256, 5, activation='relu')(img_input) #256 filters커널의개수, 5 kernel size커널의 크기 , 
# padding = valid 패딩방법으로, 제로 패딩없이 유효한 값만을 이용, window stride 1 (defalut)
x = keras.layers.MaxPool1D(2)(x)
x = keras.layers.Conv1D(128, 3 , activation='relu')(x)
x = keras.layers.MaxPool1D(2)(x)
x = keras.layers.Conv1D(16, 1, activation='relu')(x)
x = keras.layers.MaxPool1D(2)(x)

x = keras.layers.Flatten()(x)
x = keras.layers.Dense(64, activation='relu')(x)
x = keras.layers.Flatten()(x)
predictions = keras.layers.Dense(36, activation='softmax')(x)

model = keras.Model(inputs=img_input, outputs=predictions)

model.summary()

Model: "model_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_18 (InputLayer)        [(None, 16, 1)]           0         
_________________________________________________________________
conv1d_25 (Conv1D)           (None, 12, 256)           1536      
_________________________________________________________________
max_pooling1d_25 (MaxPooling (None, 6, 256)            0         
_________________________________________________________________
conv1d_26 (Conv1D)           (None, 4, 128)            98432     
_________________________________________________________________
max_pooling1d_26 (MaxPooling (None, 2, 128)            0         
_________________________________________________________________
conv1d_27 (Conv1D)           (None, 2, 16)             2064      
_________________________________________________________________
max_pooling1d_27 (MaxPooling (None, 1, 16)             0  

# 위, dense 아웃풋은 65개로, 뉴런의 수는 65개이다. 



In [ ]:
print('-'*90)

# 오류 Failed to convert a NumPy array to a Tensor (Unsupported object type int). 는 
# float형으로바꿔주며 오류고친다

In [ ]:
x_train = np.asarray(x_train).astype(int)

In [ ]:
y_train

NameError: name 'y_train' is not defined

In [ ]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train)

y_train

array([[[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       ...,

       [[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [ ]:
x_train

array([[[[91., 93., 85., 90.],
         [95., 93., 86., 91.]],

        [[87., 87., 87., 86.],
         [88., 87., 90., 87.]]],


       [[[70., 73., 69., 71.],
         [76., 76., 77., 78.]],

        [[74., 75., 76., 78.],
         [79., 80., 78., 81.]]],


       [[[65., 64., 68., 67.],
         [72., 71., 74., 73.]],

        [[73., 70., 72., 74.],
         [77., 77., 78., 78.]]],


       ...,


       [[[63., 65., 67., 68.],
         [70., 73., 76., 75.]],

        [[73., 75., 76., 78.],
         [77., 82., 81., 79.]]],


       [[[62., 65., 65., 69.],
         [72., 73., 75., 76.]],

        [[73., 72., 75., 76.],
         [79., 80., 80., 80.]]],


       [[[62., 64., 67., 68.],
         [72., 72., 73., 74.]],

        [[72., 74., 73., 75.],
         [80., 80., 80., 81.]]]])

In [ ]:
y_train = np.asarray(y_train).astype(int)

# !!!!!!!!!!!!!!!!!!!!! 모델 학습 !!!!!!!!!!!!!!!!!!!!!!!!



In [ ]:
ylabel

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2])

In [ ]:
print(one_hot_encode.shape) # 300개의 행 1개의 열 데이터 
print(x_train.shape) #300개의 행 16개의 열 데이터 
x_train = x_train.flatten()
x_train = x_train[:240]
x_train = x_train.reshape(16,5,1,3)
print("x_train.shape : " , x_train.shape) 

(16, 3)
(240,)
x_train.shape :  (16, 5, 1, 3)


In [ ]:
label.shape

(285,)

# 원 핫 인코딩

In [ ]:
print(x_train.shape)
print(one_hot_encode.shape)

(16, 5, 1, 3)
(16, 3)


In [ ]:
from tensorflow.keras.utils import to_categorical


one_hot_encode = to_categorical(ylabel)

In [ ]:


y_test = to_categorical(y_test)

In [ ]:
# 모델 학습!! 
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001, 
                                                 beta_1=0.9, 
                                                 beta_2=0.999, 
                                                 epsilon=1e-07, 
                                                 amsgrad=False,),
              loss='categorical_crossentropy',
              metrics=['accuracy'])


model.fit(x_train, one_hot_encode, epochs=400)    # 66 Epoch만 학습합니다.
# 오류는 dense 의 아웃풋 형태를 조절할 것 여기에서는 17로 줌

test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=1)
print("test_loss: {} ".format(test_loss))
print("test_accuracy: {}".format(test_accuracy))


ValueError: Data cardinality is ambiguous:
  x sizes: 285
  y sizes: 16
Make sure all arrays contain the same number of samples.

In [ ]:
# # 모델 학습!! 
# model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999),
#               loss='binary_crossentropy',
#               #sparse_categorical_crossentropy쓰면 안됨
#               metrics = [
#                 'accuracy',
#                 tf.keras.metrics.Precision(name='precision'),
#                 tf.keras.metrics.Recall(name='recall')
#                 ])


# model.fit(x_train, y_train, epochs=100)    # 66 Epoch만 학습합니다.
# # 오류는 dense 의 아웃풋 형태를 조절할 것 여기에서는 17로 줌


# 테스트 데이터로 정확도 뽑는 밑 코드 

In [ ]:
y_test = pd.DataFrame(y_test)

In [ ]:
y_test = y_test.astype(int)

In [ ]:
y_test = y_test - 1
print(y_test)

     level_0
45         2
46         2
47         2
48         2
49         2
..       ...
115        2
116        2
117        2
118        2
119        2

[75 rows x 1 columns]


In [ ]:
y_test

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [ ]:
x_test1

array([64., 65., 65., ..., 60., 62., 66.])

In [ ]:
x_test1 = x_test1.to_numpy()

In [ ]:
x_test1 = x_test1.flatten()
x_test2 = x_test1[:1125]

In [ ]:
x_test2 = x_test2.reshape(75,5,1,3)

In [ ]:
x_test1 = x_test.drop('level_0', axis = 1)

y_test = x_test.level_0

In [ ]:
y_test = y_test.astype('float')
test_scores = model.evaluate(x_test2, y_test, verbose=3)

In [ ]:
print("test loss, test acc:" , test_scores ) 

test loss, test acc: [5.173856735229492, 0.03999999910593033]


# 테스트 결과값입니다 3.9퍼센트 예측(학습데이터에서 사람2명의 데이터가 대다수, 사람3의 데이터로 학습해보니 현저히 정확도가 낮게 나옴) 을 확인하였습니다 

# 위 코드 까지 완벽?하게 먼저 해내기(cnn 돌리기)


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
# 데이터셋 로드하기
# [[your code]
data = rows
data2 = rows2
data9 = rows9
# 훈련용 데이터셋 나누기
# [[your code]
X_train = rows[:14]
X_test = rows[14:]

y_train = data9[:14]
y_test = data9[14:]

print("y_train")
print(y_train)
print('-'*90)
print('-'*90)
print("X_train")
print(X_train)
# y_test2 = data2[:16]
# y_test2 = y_test2.reshape(16,4)
# 훈련하기
# [[your code]
print('-'*90)



In [ ]:
# from sklearn.linear_model import RidgeClassifierCV
# clf = RidgeClassifierCV().fit(X_train, y_train)

# roc_auc_score(rows4, rows5, average=None)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.svm import SVC
from sklearn.svm import SVR


# 데이터셋 로드하기
# [[your code]
data = rows
data2 = rows2
data9 = rows9
# 훈련용 데이터셋 나누기
# [[your code]
X_train = rows[:14]
X_test = rows[14:]

y_train = data9[:14]
y_test = data9[14:]

z_train = data9[:14]

print("y_train")
print(y_train)
print('-'*90)
print('-'*90)
print("X_train")
print(X_train)
# y_test2 = data2[:16]
# y_test2 = y_test2.reshape(16,4)
# 훈련하기
# [[your code]
print('-'*90)
print('-'*90)

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
# X2, y2 = make_classification(n_samples=1000, n_features=4,
#                              n_informative=2, n_redundant=0,
#                              random_state=0, shuffle=False)
# clf = RandomForestClassifier(max_depth=2, random_state=0)
# clf.fit(X2, y2)
# print(X2)
# print('-/'*90)
# print('-/'*90)
xtt = np.array(X_train)
xt = xtt.reshape(-1,)
ytt = np.array(y_train) #numpy array 로 바꿈!!
yt = ytt.reshape(-1,) # numpy array 차원 축소!!! 1차원으로 만들어주기
ett = np.array(y_test)
ettt = ett.reshape(-1,)
zt = np.array(z_train)

print("xt : X_train 에 해당")
print(xt)
print('-'*90)
print("yt: y_train 에 해당 ")
print(yt)
print('-'*90)
print("ett : y_test 에 해당")
print(ettt)
print('-'*90)


#열이 16개인 데이터셋


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.svm import SVC
from sklearn.svm import SVR


# 데이터셋 로드하기
# [[your code]
data = rows
data2 = rows2
data9 = rows9
# 훈련용 데이터셋 나누기
# [[your code]
X_train = rows[:14]
X_test = rows[14:]

y_train = data9[:14]
y_test = data9[14:]

z_train = data9[:14]

print("y_train")
print(y_train)
print('-'*90)
print('-'*90)
print("X_train")
print(X_train)
# y_test2 = data2[:16]
# y_test2 = y_test2.reshape(16,4)
# 훈련하기
# [[your code]
print('-'*90)
print('-'*90)

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
# X2, y2 = make_classification(n_samples=1000, n_features=4,
#                              n_informative=2, n_redundant=0,
#                              random_state=0, shuffle=False)
# clf = RandomForestClassifier(max_depth=2, random_state=0)
# clf.fit(X2, y2)
# print(X2)
# print('-/'*90)
# print('-/'*90)
xtt = np.array(X_train)
xt = xtt.reshape(-1,)
ytt = np.array(y_train) #numpy array 로 바꿈!!
yt = ytt.reshape(-1,) # numpy array 차원 축소!!! 1차원으로 만들어주기
ett = np.array(y_test)  
ettt = ett.reshape(-1,)
zt = np.array(z_train)

print("xt : X_train 에 해당")
print(xt)
print('-'*90)
print("yt: y_train 에 해당 ")
print(yt)
print('-'*90)
print("ett : y_test 에 해당")
print(ettt)
print('-'*90)

xt = np.expand_dims(xt, axis=0) # 차원 확대
yt = np.expand_dims(yt, axis=0) # 차원 확대 
xt0909 = np.expand_dims(xt, axis=0)
np.expand_dims(yt, axis=0)
print("xt0909")
print(xt0909)
print("xt")
print(xt)
print('-'*90)
print("yt")
print(yt)
print('-'*90)
print('-*'*90)
# clf = MultiOutputClassifier(KNeighborsClassifier()).fit(xt,yt) # 2차원 이상의 배열이 필요함...
knn = KNeighborsClassifier(n_neighbors=88)#여기에서 n_neighbers =1 이 중요!!! 입력 데이터 형태를 보면 1로 해야함
knn = MultiOutputClassifier(KNeighborsClassifier(n_neighbors=1)).fit(xt,yt) #2차원 필요
print("knn 예측치")
knnmaster1 = knn.predict(xt[-2:]) #We select the training set with the [:-1] Python syntax,
#which produces a new array that contains all but the last item from digits.data:
print("knmaster1")
print(knnmaster1)
print('-*'*90)


print("정답률=", knn.score(yt, xt)) ###########################


print('-*'*90)
model = RandomForestClassifier()
model.fit(xt, yt)
print('-'*90)
# 예측하기
# [[your code]
y_pred1 = model.predict(xt)
# 정답률 출력하기
# [[your code]
print("randomforest 예측치 : " )
print(y_pred1)

print('-'*90)


decision_tree = DecisionTreeClassifier(random_state=255,min_samples_split=5,max_depth=6)
decision_tree.fit(xt, yt)
y_pred2 = decision_tree.predict(xt)
print("Decision Tree classifier 예측치")
print(y_pred2)
print('-'*90)

y_testt = np.transpose(y_test)
print(y_test)
print('-'*90)
#y_test = np.expand_dims(y_test, axis=0)

print('decision tree 테스트 : y_test')
print(y_test)
print('-'*90)
print('decision tree 예측치 : y_pred1')
print(y_pred1)
print('-'*90)
print('-'*90) 
#svm 은 y 가 1차원이어야 한다고 한다.
yt2 = yt.reshape(-1,) # numpy array 차원 축소!!! 1차원으로 만들어주기
xt2 = xt.reshape(-1,)
xt3 = xt2.reshape(-1, 1)
yt3 = yt2.reshape(-1, 1) #조진호(사람2) 데이터            
ett2 = ett.reshape(-1,)
ett3 = ett.reshape(-1, 1) #최주원(사람3) 데이터
zt3 = zt.reshape(-1,)
zt3 = zt.reshape(-1,1)

print("zt3")
print(zt3)
print('--'*60)
print("xt2 : xt를 reshape 으로(-1,) 한 결과 ")
print(xt2)
print('--'*90)
print("xt3 : xt2를 reshape 으로 (-1,1)한 결과 ")
print(xt3)
print('--'*90)
from sklearn import svm

print('-'*90)
print('-'*90)


ett4 =ett3.reshape(-1,)
yt33 = yt3.reshape(-1,) #차원축소
xt33 = xt3.reshape(-1,)

print('--'*90)

yt4 = yt3.reshape(-1,)
ett3= ett3.reshape(-1,)

print(ett4)
yt5 = yt4[:96]

accuracy = accuracy_score(ett4, yt5) #같은 shape 이어야 함. accuracy 랑 다른게 있다. 


In [ ]:


print("정확도 계산중... ")
print(" 정확도는 다음과 같다 ")
print(accuracy*100)
# from sklearn.datasets import make_blobs
# import matplotlib.pyplot as plt

# X,y = make_multilabel_classification(n_classes= 3,random_state = 0)

# clf.predict(X[-2:])
yt999 = yt3.reshape(-1,1)
ytridge2 = yt999.reshape(-1,)
xt35 = xt3.reshape(-1,1)
# knn = KNeighborsClassifier(n_neighbors=3)
# classifier = MultiOutputClassifier(knn, n_jobs=-1)
# classifier.fit(y_test,y_pred)
# predictions = classifier.predict(y_train)
# classifier.score(y_true,np.array(y_train))

from sklearn.linear_model import RidgeClassifierCV
clf = RidgeClassifierCV(cv = 5, normalize = True,).fit(xt35 , yt999) #1d array 필요 .ravel() 써서 평평하게 함 
y_score = clf.decision_function(yt999) #2d array 필요 
print("ridgeclassifier 스코어")
print(y_score)

# from sklearn.datasets import make_multilabel_classification
# from sklearn.multioutput import MultiOutputClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import roc_auc_score

# X, y = make_multilabel_classification(random_state=0)
# inner_clf = LogisticRegression(solver="liblinear", random_state=0)
# clf = MultiOutputClassifier(inner_clf).fit(X, y)
# y_score = np.transpose([y_pred[:, 1] for y_pred in clf.predict_proba(X)])
# roc_auc_score(y, y_score, average=None)
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import make_circles
from sklearn import datasets
import scipy.stats as stats
import seaborn as sns
fig = plt.figure(figsize=(6, 6))


# clf9 = Pipeline([
#   ('feature_selection', SelectFromModel(LinearSVC(penalty="l1"))),
#   ('classification', RandomForestClassifier())
# ])
ett999 = ett3.reshape(-1,1)

gbrt = GradientBoostingClassifier(learning_rate=0.1,n_estimators =650,max_leaf_nodes=None, random_state=0,max_depth=6)
gbrt.fit(xt3, yt3)
print("gbrt결정 함수의 결과 형태: {}".format(gbrt.decision_function(yt999).shape))#2차원 요구--> ett3
# plot the first few entries of the decision function
print("gbrt결정 함수 결과:\n{}".format(gbrt.decision_function(yt999)[:6, :]))
print('/*/'*90)
print("gbrt가장 큰 결정 함수의 인덱스:\n{}".format(
      np.argmax(gbrt.decision_function(yt999), axis=1)))
print("gbrt예측:\n{}".format(gbrt.predict(yt999)))
print("gbrt 스코어")
print(gbrt.score(xt3,yt3))

# 가장 큰 결정 함수의 인덱스:
# [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
#  0]
# 예측:
# [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
#  0]
print('/*/'*90)
# predict_proba 결과 중 앞부분 일부를 확인합니다
print("예측 확률:\n{}".format(gbrt.predict_proba(yt999)[:9]))
# 행 방향으로 확률을 더하면 1 이 됩니다
print("합: {}".format(gbrt.predict_proba(yt999)[:9].sum(axis=1)))
# 예측 확률:
# [[0.10664722 0.7840248  0.10932798]
#  [0.78880668 0.10599243 0.10520089]
#  [0.10231173 0.10822274 0.78946553]
#  [0.10664722 0.7840248  0.10932798]
#  [0.10825347 0.66344934 0.22829719]
#  [0.78880668 0.10599243 0.10520089]]
# 합: [1. 1. 1. 1. 1. 1.]
print('/*/'*90)
x8x8 = pd.DataFrame(gbrt.decision_function(ett999))

x9x9 = x8x8.corr()

e9e9 = sns.heatmap(x9x9, cmap = 'viridis')

e0e0 = sns.scatterplot(xt33,yt33)
plt.show()
print('/*/'*90)
print(e0e0)
print('/*/'*90)

x88x88 = pd.DataFrame(gbrt.decision_function(yt999))
x99x99 = x88x88.corr()
e99e99 = sns.heatmap(x99x99, cmap = 'viridis')
# e0e0 = sns.scatterplot(xt33,yt33)
plt.show()

print(e99e99)





xt39 = np.transpose(xt3)
yt39 = np.transpose(yt3)
ett39 = np.transpose(ett3)
zt39 = np.transpose(zt3)
print("zt39")
print(zt39.shape)
print(zt39)
print('/*/'*90)
s = [0.7*np.linalg.norm([a, b]) for a, b in zip(xt3, yt3)]
s = [a / max(s) for a in s]  # scale
print("ett3.shape")
print(ett3.shape)
print('/*/'*90)
print("xt39.shape :xt39 = np.transpose(xt3)")
print(xt39.shape)
print('/*/'*90)
print("xt39")
print(xt39)


In [ ]:

ax= plt.scatter(xt39[:300], yt39[:300], c=s, s=30, cmap=plt.cm.Paired)
clf = SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.2, gamma=0.2,
  kernel='rbf', shrinking=True, tol=0.001)#파이프라인만들기

clf.fit(xt3,yt3) #2차원으로 fit X(왼쪽 xt3)에는 포인트가 있고 Y에는 해당 포인트가 속한 클래스가 있습니다.

# 초평면(Hyper-Plane) 표현
ax = plt.gca()
xlim = ax.get_xlim()
ylim = ax.get_ylim()
xx = np.linspace(xlim[0], xlim[1], 30)
yy = np.linspace(ylim[0], ylim[1], 30)
YY, XX = np.meshgrid(yy, xx)
print("XX.shape :np.meshgrid(yy, xx)")
print(XX.shape)



xy = np.vstack([XX.ravel(), YY.ravel()]).T
print("xy.shape : np.vstack([XX.ravel(), YY.ravel()]).T ")
print(xy.shape)
xy = xy.reshape(-1,1)


xy1 = xy[:30]
xy1 = xy1.flatten()
xy1 = xy1[:899]
print("xy1")
print(xy1)
xy1 = xy1.reshape(-1,1)#$$$
xy2 = xy1[:30]#$$$
xy3 = xy2.flatten()#$$$
print("xy3")
print(xy3)
xy3 = xy3[:30]
xy99 = xy3.reshape(30,)#$$$
print("xy3")
print(xy3)
xy5= xy99.reshape(-1,1)#$$$
# print("clfdecisionfuction")
# print(fig.add_subplot(112, clf.decision_function(xy5)))
# Z = clf.decision_function(xy5).reshape(30,30)
# Z = clf.decision_function(xy5).reshape(-1,)#1차원으로 만들기
# print(Z)
# Z = Z[:900] # 900개까지 나열
# Z = Z.reshape(30,30) #30*30 행렬로 reshape
# ax.contour(XX, YY, Z, colors='k', levels=[-1,0,1], alpha=0.9, linestyles=['--', '-', '--'])
# # 지지벡터(Support Vector) 표현 
# ax.scatter(clf.support_vectors_[:,1], clf.support_vectors_[:,1], s=60, facecolors='r')
# plt.show()
# fig = plt.figure(figsize=(12, 12))


# ax2 = fig.add_subplot(111, projection='3d')
# ax2.scatter(xt39[:100], yt39[:100], yt39[:100], c= s , marker='o', s=15, cmap='Greens')

# print(yt3.shape)
# yt4 = yt3.reshape(-1,)
# print(yt4)
# print("ett4")
# print(ett4)
# yt5 = yt4[:96]
# print("yt5")
# print(yt5)
# accuracy = accuracy_score(ett4, yt5) #같은 shape 이어야 함. accuracy 랑 다른게 있다. 


# print("정확도 계산중... ")
# print(" 정확도는 다음과 같다 ")
# print(accuracy*100)



In [ ]:
from sklearn import svm
# from sklearn.datasets import make_blobs
# import matplotlib.pyplot as plt

# X,y = make_multilabel_classification(n_classes= 3,random_state = 0)

# clf.predict(X[-2:])


# knn = KNeighborsClassifier(n_neighbors=3)
# classifier = MultiOutputClassifier(knn, n_jobs=-1)
# classifier.fit(y_test,y_pred)
# predictions = classifier.predict(y_train)
# classifier.score(y_true,np.array(y_train))

# from sklearn.linear_model import RidgeClassifierCV
# clf = RidgeClassifierCV().fit(X_train, y_train)
# y_score = clf.decision_function(X_train)
# roc_auc_score(y_test, y_train, average=None)

# from sklearn.datasets import make_multilabel_classification
# from sklearn.multioutput import MultiOutputClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import roc_auc_score

# X, y = make_multilabel_classification(random_state=0)
# inner_clf = LogisticRegression(solver="liblinear", random_state=0)
# clf = MultiOutputClassifier(inner_clf).fit(X, y)
# y_score = np.transpose([y_pred[:, 1] for y_pred in clf.predict_proba(X)])
# roc_auc_score(y, y_score, average=None)
clf = svm.SVC(kernel="linear", C=1000)
x__train = xt3.reshape(-1,1)
y__train = yt3.reshape(-1,1)

clf.fit(x__train, y__train)
print(xt3.shape)
print(yt3.shape)
s = [0.1*np.linalg.norm([a, b]) for a, b in zip(xt3, yt3)]
s = [a / max(s) for a in s]  # scale

plt.scatter(xt3[:224], xt3[:224], c=s, s=30, cmap=plt.cm.Paired)

# decision function 표현 초평면(Hyper-Plane) 표현
ax = plt.gca()
xlim = ax.get_xlim()
ylim = ax.get_ylim()
# plot decision boundary and margins
# Z = clf.decision_function(xy).reshape(XX.shape)

ax.contour(XX, YY, colors="k", levels=[-1, 0, 1], alpha=0.5, linestyles=["--", "-", "--"])

xx = np.linspace(xlim[0], xlim[1], 30)
yy = np.linspace(ylim[0], ylim[1], 30)
YY, XX = np.meshgrid(yy, xx)
xy = np.vstack([XX.ravel(), YY.ravel()])



# plot decision boundary and margins
ax.contour(XX, YY, colors="k", levels=[-1, 0, 1], alpha=0.5, linestyles=["--", "-", "--"])

# 지지벡터(Support Vector) 표현
ax.scatter(
    clf.support_vectors_[:, 0],
    clf.support_vectors_[:, 1],
    s=100,
    linewidth=1,
    facecolors="none",
    edgecolors="k",
)
plt.show()